# Generated by Django 3.0.7 on 2020-11-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='anothernumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
