# Generated by Django 3.0.7 on 2020-11-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_anothernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='anothernumber',
            field=models.IntegerField(default=0),
        ),
    ]
