# Generated by Django 3.0.7 on 2020-11-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201124_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='pune', max_length=20),
        ),
    ]
