# Generated by Django 3.0.7 on 2020-11-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_pname'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='staus',
            field=models.BooleanField(default='False'),
        ),
    ]
