# Generated by Django 3.0.7 on 2020-11-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_staus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='staus',
            new_name='status',
        ),
    ]
